object Libs {
    const val ANALYTICS = "com.google.firebase:firebase-analytics"
    const val ANDROID_BROWSER_HELPER =
        "com.google.androidbrowserhelper:androidbrowserhelper"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val ANDROIDX_HILT_VIEW_MODEL = "androidx.hilt:hilt-lifecycle-viewmodel"
    const val ANDROIDX_TEST_EXT = "androidx.test.ext:junit"
    const val ANDROIDX_TEST_ESPRESSO = "androidx.test.espresso:espresso-core"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CRASHLYTICS = "com.google.firebase:firebase-crashlytics"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val MOCKITO = "org.mockito:mockito-inline"
    const val MOSHI = "com.squareup.moshi:moshi"
    const val MOSHI_KOTLIN = "com.squareup.moshi:moshi-kotlin"
    const val MOSHI_KOTLIN_CODEGEN = "com.squareup.moshi:moshi-kotlin-codegen"
    const val NAVIGATION_DYNAMIC_FEATURES_FRAGMENT =
        "androidx.navigation:navigation-dynamic-features-fragment"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_TEST = "androidx.navigation:navigation-testing"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val OSS_LICENSES = "com.google.android.gms:play-services-oss-licenses"
    const val PERF = "com.google.firebase:firebase-perf"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val RECYCLER_VIEW_SELECTION = "androidx.recyclerview:recyclerview-selection"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_CONVERTER_MOSHI = "com.squareup.retrofit2:converter-moshi"
    const val TIMBER = "com.jakewharton.timber:timber"
}
