name: 'Setup JDK & Gradle & debug.keystore'
description: 'Android CIの初期設定。JDKセットアップとdebug.keystoreの出力'
inputs:
  debug-keystore-base64:
    description: "debug.keystoreをBase64エンコードしたものを指定"
    required: false
  google_service_json_base64:
    description: "google-service.jsonをBase64エンコードしたものを指定"
    required: false
runs:
  using: "composite"
  steps:
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: set up Gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
    - name: Write debug.keystore
      shell: bash
      run: |
        if [ -n "${{ inputs.debug-keystore-base64 }}" ]; then
          echo ${{ inputs.debug-keystore-base64 }} | base64 -d > ./debug.keystore;
        fi;
    - name: Write google-services.json
      shell: bash
      run: |
        if [ -n "${{ inputs.google_service_json_base64 }}" ]; then
          echo ${{ inputs.google_service_json_base64 }} | base64 -d > ./app/google-services.json;
        fi;
