name: Android CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-jdk-gradle-keystore
        with:
          debug-keystore-base64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
      - name: Run ktlint
        run: ./gradlew ktlintCheck
      - name: Archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./reports
          retention-days: 3
  android-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-jdk-gradle-keystore
        with:
          debug-keystore-base64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
          google_service_json_base64: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64 }}
      - name: Run Android lint
        run: ./gradlew lintDebug
      - name: Archive reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./reports
          retention-days: 3
  danger:
    if: cancelled() != true
    runs-on: ubuntu-latest
    needs: [ktlint,android-lint]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-jdk-gradle-keystore
        with:
          debug-keystore-base64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
          google_service_json_base64: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64 }}
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Setup bundler
        run: |
          gem install danger
          gem install danger-checkstyle_format
          gem install danger-android_lint
          gem install danger-junit
      - name: Download reports
        uses: actions/download-artifact@v2
        with:
          name: reports
          path: ./reports
      - name: ls
        run: ls ./reports
      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          danger --verbose
